sudo: true

language: java

before_cache:
  - rm -rf $HOME/.m2/repository/org/antlr
  - sudo apt-get -y install clang-6.0
  - sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-6.0 100
cache:
  timeout: 600
  directories:
  - $HOME/.m2
  - $HOME/Library/Caches/Antlr4
  - $HOME/Library/Caches/Homebrew

stages:
#  - smoke-test
#  - main-test
  - extended-test

matrix:
  include:
    - os: linux
      dist: xenial
      compiler: clang
      env:
       - TARGET=swift
       - GROUP=ALL
      stage: extended-test
    - os: linux
      arch: s390x
      dist: bionic
      compiler: clang
      addons:
        apt:
          update: true
          packages: 
          - clang-6.0
      env:
       - TARGET=swift
       - GROUP=ALL
      stage: extended-test


before_install:
  - f="./.travis/before-install-$TRAVIS_OS_NAME-$TARGET.sh"; ! [ -x "$f" ] || "$f"

script:
  - |
    cd runtime-testsuite;
    travis_wait 40 ../.travis/run-tests-$TARGET.sh
    rc=$?
    cat target/surefire-reports/*.dumpstream || true
    exit $rc
